/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.setup.SetupSolverDialog;
import GUI.solver.EvolutionEventListener;
import GUI.solver.UIexperiment;
import GUI.solver.UiSolver;
import GUI.statistics.StatisticsChartExperiment;
import com.evolutionary.solver.EAsolver;
import com.evolutionary.solver.MuGA;
import com.evolutionary.solverUtils.EAexperiment;
import com.evolutionary.solverUtils.FileSimulation;
import com.evolutionary.solverUtils.FileSolver;
import java.io.File;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author zulu
 */
public class ExploreSimulation extends javax.swing.JFrame {

    //main meno of this frame
    JFrame mainMenu;
    EAexperiment simulation = new EAexperiment();
    UIexperiment uiSolver = new UIexperiment();

    StatisticsChartExperiment statsPanel;

    int selectedSolverIndex = -1;

    /**
     * Creates new form ExploreSolver
     */
    public ExploreSimulation(JFrame mainMenu) {
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        initComponents();
        this.mainMenu = mainMenu;
        initMyComponents();
    }

    public void initMyComponents() {
        DefaultListModel<String> model = new DefaultListModel<>();
        lstSolvers.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btMenu = new javax.swing.JButton();
        btStart = new javax.swing.JButton();
        btRun = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        txtPathSimulation = new javax.swing.JLabel();
        pnSolver_Pop = new javax.swing.JPanel();
        tpSolver = new javax.swing.JTabbedPane();
        pnSetupSolver = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        btNew = new javax.swing.JButton();
        btOpen1 = new javax.swing.JButton();
        btEdit = new javax.swing.JButton();
        btClone = new javax.swing.JButton();
        btSave = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtSolver = new javax.swing.JTextArea();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstSolvers = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btMenu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Main_Menu-32.png"))); // NOI18N
        btMenu.setText("Menu");
        btMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btMenuActionPerformed(evt);
            }
        });

        btStart.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Solver_start_32.png"))); // NOI18N
        btStart.setText("Start simulation");
        btStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btStartActionPerformed(evt);
            }
        });

        btRun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Run_32.png"))); // NOI18N
        btRun.setText("Run");
        btRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRunActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(btStart)
                .addGap(141, 141, 141)
                .addComponent(btRun, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 243, Short.MAX_VALUE)
                .addComponent(btMenu))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btStart)
                        .addComponent(btRun))
                    .addComponent(btMenu))
                .addGap(0, 13, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.NORTH);

        txtPathSimulation.setText("./");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtPathSimulation, javax.swing.GroupLayout.DEFAULT_SIZE, 795, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(txtPathSimulation))
        );

        getContentPane().add(jPanel3, java.awt.BorderLayout.SOUTH);

        pnSolver_Pop.setLayout(new java.awt.BorderLayout());

        pnSetupSolver.setLayout(new java.awt.BorderLayout());

        btNew.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/DNA-24.png"))); // NOI18N
        btNew.setText("New");
        btNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNewActionPerformed(evt);
            }
        });

        btOpen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/File_Open-24.png"))); // NOI18N
        btOpen1.setText("Open");
        btOpen1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOpen1ActionPerformed(evt);
            }
        });

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Setup_Solver-24.png"))); // NOI18N
        btEdit.setText("Edit");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        btClone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/reload_24.png"))); // NOI18N
        btClone.setText("Clone");
        btClone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCloneActionPerformed(evt);
            }
        });

        btSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/GUI/icons/Delete-24.png"))); // NOI18N
        btSave.setText("Delete");
        btSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btOpen1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btClone, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btNew, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btOpen1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btClone, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(btSave, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pnSetupSolver.add(jPanel6, java.awt.BorderLayout.NORTH);

        txtSolver.setColumns(20);
        txtSolver.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtSolver.setRows(5);
        jScrollPane3.setViewportView(txtSolver);

        pnSetupSolver.add(jScrollPane3, java.awt.BorderLayout.CENTER);

        lstSolvers.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        lstSolvers.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                lstSolversValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(lstSolvers);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 356, Short.MAX_VALUE)
        );

        pnSetupSolver.add(jPanel2, java.awt.BorderLayout.LINE_START);

        tpSolver.addTab("Experiment", pnSetupSolver);

        pnSolver_Pop.add(tpSolver, java.awt.BorderLayout.CENTER);

        getContentPane().add(pnSolver_Pop, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btMenuActionPerformed
        this.dispose();
        mainMenu.setVisible(true);

    }//GEN-LAST:event_btMenuActionPerformed

    private void btNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNewActionPerformed
        EAsolver s = new MuGA();
        s.numberOfRun = 32;
        simulation.solvers.add(s);
        displaySolvers();
        lstSolvers.setSelectedIndex(simulation.solvers.size() - 1);

    }//GEN-LAST:event_btNewActionPerformed

    public void updateSelectedSolver() {
        if (selectedSolverIndex >= 0 && !txtSolver.getText().equalsIgnoreCase(simulation.solvers.get(selectedSolverIndex).toString())) {
            EAsolver solver = FileSolver.loadSolver(txtSolver.getText(), "");
            if (solver != null) {
                simulation.solvers.set(selectedSolverIndex, solver);
                displaySolvers();
            }
        }
    }

    private void displaySolvers() {
        DefaultListModel lst = new DefaultListModel();
        DefaultListModel old = (DefaultListModel) lstSolvers.getModel();
        boolean update = false;
        for (int i = 0; i < simulation.solvers.size(); i++) {
            if (old.size() > i && !old.getElementAt(i).toString().equalsIgnoreCase(simulation.solvers.get(i).solverName)) {
                update = true;
            }
            lst.addElement(simulation.solvers.get(i).solverName);
        }
        if (update || lst.size() != old.size()) {
            lstSolvers.setModel(lst);
            lstSolvers.setSelectedIndex(selectedSolverIndex);
        }
    }


    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        EAsolver s = FileSolver.loadSolver(txtSolver.getText(), txtPathSimulation.getText());
        if (s == null) {
            return;
        }
        SetupSolverDialog setup = new SetupSolverDialog(s);
        simulation.solvers.set(selectedSolverIndex, setup.solver);
        txtSolver.setText(setup.solver.toString());
        displaySolvers();

    }//GEN-LAST:event_btEditActionPerformed

    private void btSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSaveActionPerformed
        if (selectedSolverIndex >= 0) {
            simulation.solvers.remove(selectedSolverIndex);
            txtSolver.setText("");
            if (simulation.solvers.size() > selectedSolverIndex) {
                displaySolvers();
            } else {
                selectedSolverIndex--;
                displaySolvers();
            }
        }
    }//GEN-LAST:event_btSaveActionPerformed


    private void btStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btStartActionPerformed
        uiSolver.initExperiment(simulation.solvers);
        initStatisticsPanels(); //create statistics panels        
        for (int i = 0; i < simulation.solvers.size(); i++) {
            uiSolver.addListener(i, new EvolutionEventListener() {
                @Override
                public void onEvolutionChanges(EAsolver source) {
                    statsPanel.updateStats(source);
                }

                @Override
                public void onEvolutionComplete(EAsolver source) {
                    simulation.stopEvolution(source);
                    if (simulation.isDone()) {
                        System.out.println("DONE . . .");
                        //display final result
                    }
                }
            });
        }
        uiSolver.startSolvers();
        btRun.setSelected(true);
        btRun.setText("Stop");
    }//GEN-LAST:event_btStartActionPerformed

    private void initStatisticsPanels() {
        //load solver from textArea
        updateSelectedSolver();

        int selectedIndex = tpSolver.getSelectedIndex();
        //initialize simulation
        simulation.startEvolution();
        //remove all tabs from GUI
        tpSolver.removeAll();
        //create new Tabs

        statsPanel = new StatisticsChartExperiment(simulation.solvers);

        //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: SETUP and POPULATION
        tpSolver.addTab("Experiment", pnSetupSolver);
        //:::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::: STATISTICS
        int totalTabs = statsPanel.getTabs().getTabCount();
        for (int i = 0; i < totalTabs; i++) {
            tpSolver.addTab(statsPanel.getTabs().getTitleAt(0), statsPanel.getTabs().getComponentAt(0));
        }

        if (selectedIndex < tpSolver.getTabCount()) {
            tpSolver.setSelectedIndex(selectedIndex);
        }
        this.revalidate();
        this.repaint();
    }

    private void btRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRunActionPerformed
        if (!btRun.isSelected()) {
            uiSolver.stopSolvers();
            btRun.setText("Continue");
        } else {
            uiSolver.startSolvers();
            btRun.setText("Stop");
        }

    }//GEN-LAST:event_btRunActionPerformed

    private void btOpen1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOpen1ActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File(txtPathSimulation.getText()));
        file.setSelectedFile(new File(txtPathSimulation.getText()));
        file.setFileFilter(new FileNameExtensionFilter("Muga Simulation Files", FileSolver.FILE_EXTENSION));
        int returnVal = file.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            ArrayList<EAsolver> sims = FileSimulation.loadSimulation(file.getSelectedFile().getPath());
            if (sims.size() > 0) {
                simulation.solvers.addAll(sims);
                displaySolvers();
            }
        }
    }//GEN-LAST:event_btOpen1ActionPerformed

    private void btCloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCloneActionPerformed
        if (lstSolvers.getSelectedIndex() >= 0) {
            EAsolver s = FileSolver.loadSolver(txtSolver.getText(), txtPathSimulation.getText());
            if (s == null) {
                return;
            }
            simulation.solvers.add(s);
            displaySolvers();
            lstSolvers.setSelectedIndex(simulation.solvers.size() - 1);
        }


    }//GEN-LAST:event_btCloneActionPerformed

    private void lstSolversValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_lstSolversValueChanged
        updateSelectedSolver();
        if (lstSolvers.getSelectedIndex() >= 0) {
            txtSolver.setText(simulation.solvers.get(lstSolvers.getSelectedIndex()).toString());
            selectedSolverIndex = lstSolvers.getSelectedIndex();
        } else {
            txtSolver.setText("");
            selectedSolverIndex = -1;
        }
    }//GEN-LAST:event_lstSolversValueChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploreSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploreSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploreSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploreSimulation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExploreSimulation(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btClone;
    private javax.swing.JButton btEdit;
    private javax.swing.JButton btMenu;
    private javax.swing.JButton btNew;
    private javax.swing.JButton btOpen1;
    private javax.swing.JToggleButton btRun;
    private javax.swing.JButton btSave;
    private javax.swing.JButton btStart;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JList<String> lstSolvers;
    private javax.swing.JPanel pnSetupSolver;
    private javax.swing.JPanel pnSolver_Pop;
    private javax.swing.JTabbedPane tpSolver;
    private javax.swing.JLabel txtPathSimulation;
    private javax.swing.JTextArea txtSolver;
    // End of variables declaration//GEN-END:variables

}
