package com.HBOA;

import java.util.Random;


public class HBOA_original{
	
	private static String paramFile;
	public static int         nRuns;				 	// Number of runs to perform with the same problem.
	public static int	   nSuccess = 0;	 		 	// Number of successful runs;
	
	public static Random     random = new Random();  	// Random global object. Use this to generate any random sequence in any file.	
	
	
	public static void main(String[] args){
//		random.setSeed(654321);						 	// Fixing the seed will also fix the random generator.
		 											 	// sequence generated by Random class. This is for testing only!
		paramFile = "HBOAParameters.txt";						 	// Check Run->RunConfigurations...-> Arguments to set the Parameter File name.  
		HBOASolver solver = new HBOASolver(paramFile); 	// Initialize the HBOA_original solver and Problem 'problem'.
		HBOAPress.printInitialInfo();
		for(int r = 0; r < HBOA_original.nRuns; r++){		 	// Perform 'nRuns' for the same problem.
			HBOAPress.printRunInitialInfo(r);	
			nSuccess += solver.solve(r);    				// Solve Problem 'problem'.
			HBOAPress.printRunFinalInfo(r);			
		}
		HBOAPress.printFinalInfo();
	}
}
