/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI.setup;

import GUI.DisplayProblem.DisplayPopulation;
import GUI.utils.MuGASystem;
import com.evolutionary.population.SimplePopulation;
import com.evolutionary.problem.Solution;
import java.awt.BorderLayout;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author zulu
 */
public class UIpopulation extends javax.swing.JPanel {

    public SimplePopulation myPopulation;

    /**
     * Creates new form UIpopulation
     */
    public UIpopulation() {
        initComponents();
    }

    public void setPopulation(SimplePopulation pop) {
        if (pop == null || pop.isEmpty()) {
            return;
        }
        Solution ind = pop.getIndividual(0);
        ArrayList display = MuGASystem.getObjects(MuGASystem.GRAPHICS);
        DefaultComboBoxModel model = new DefaultComboBoxModel();
        for (Object object : display) {
            try {// try build display
                if (((DisplayPopulation) object).isValid(ind)) {
                    model.addElement(object);
                }
            } catch (Exception e) {
                //display not avaiable
            }
        }
        cbGraphicsDisplay.setModel(model);
        cbGraphicsDisplay.setSelectedIndex(model.getSize() - 1);
        updatePopulation(pop);
    }

    public DisplayPopulation getPopulationGraphics() {
        return (DisplayPopulation) cbGraphicsDisplay.getSelectedItem();
    }

    public synchronized void updatePopulation(SimplePopulation pop) {
        myPopulation = pop;
        tpDisplayPopStateChanged(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpDisplayPop = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtPopulation = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtPhenotype = new javax.swing.JTextArea();
        grPopulation = new javax.swing.JPanel();
        cbGraphicsDisplay = new javax.swing.JComboBox<>();

        setLayout(new java.awt.BorderLayout());

        tpDisplayPop.setTabPlacement(javax.swing.JTabbedPane.BOTTOM);
        tpDisplayPop.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tpDisplayPopStateChanged(evt);
            }
        });

        txtPopulation.setEditable(false);
        txtPopulation.setColumns(20);
        txtPopulation.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtPopulation.setRows(5);
        jScrollPane1.setViewportView(txtPopulation);

        tpDisplayPop.addTab("Genotype", jScrollPane1);

        txtPhenotype.setColumns(20);
        txtPhenotype.setFont(new java.awt.Font("Courier New", 0, 14)); // NOI18N
        txtPhenotype.setRows(5);
        jScrollPane2.setViewportView(txtPhenotype);

        tpDisplayPop.addTab("Phenotype", jScrollPane2);

        grPopulation.setLayout(new java.awt.BorderLayout());

        cbGraphicsDisplay.setBackground(new java.awt.Color(0, 204, 204));
        cbGraphicsDisplay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbGraphicsDisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbGraphicsDisplayActionPerformed(evt);
            }
        });
        grPopulation.add(cbGraphicsDisplay, java.awt.BorderLayout.PAGE_START);

        tpDisplayPop.addTab("Graphics", grPopulation);

        add(tpDisplayPop, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void cbGraphicsDisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbGraphicsDisplayActionPerformed
        if (cbGraphicsDisplay.getSelectedIndex() < 0 || myPopulation == null) {
            return;
        }
        grPopulation.removeAll();
        DisplayPopulation display = (DisplayPopulation) cbGraphicsDisplay.getSelectedItem();
        display.setPopulation(myPopulation);
        grPopulation.add(display, BorderLayout.CENTER);
        grPopulation.add(cbGraphicsDisplay, BorderLayout.NORTH);
        grPopulation.revalidate();
        grPopulation.repaint();
    }//GEN-LAST:event_cbGraphicsDisplayActionPerformed

    private void tpDisplayPopStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tpDisplayPopStateChanged
        if (myPopulation == null) {
            return;
        }
        if (tpDisplayPop.getSelectedIndex() == 0) {
            txtPopulation.setText(myPopulation.toString());
            txtPopulation.setCaretPosition(0);
        } else if (tpDisplayPop.getSelectedIndex() == 1) {
            txtPhenotype.setText(getPopPhenotypeString(myPopulation));
            txtPhenotype.setCaretPosition(0);
        } else {

            cbGraphicsDisplayActionPerformed(null);
        }
    }//GEN-LAST:event_tpDisplayPopStateChanged

    public String getPopPhenotypeString(SimplePopulation pop) {
        if (pop.isEmpty()) {
            return "Empty Population";
        }
        pop.sort();
        List<Solution> lst = pop.getList();

        StringBuilder txt = new StringBuilder(pop.getClass().getSimpleName() + " ");
        txt.append(" " + pop.getNumberOfIndividuals());
        txt.append(" Individuals  ");
        txt.append(lst.get(0).getName() + "\n");
        for (int i = 0; i < lst.size(); i++) {
            txt.append(lst.get(i).toStringPhenotypeIndividual() + "\n");
        }
        return txt.toString();
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGraphicsDisplay;
    private javax.swing.JPanel grPopulation;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tpDisplayPop;
    private javax.swing.JTextArea txtPhenotype;
    private javax.swing.JTextArea txtPopulation;
    // End of variables declaration//GEN-END:variables
}
