/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package zzz_test.events;

import javax.swing.event.EventListenerList;

/**
 *
 * @author zulu
 */
public class EventPanel extends javax.swing.JPanel {

    /**
     * Creates new form EventPanel
     */
    public EventPanel() {
        initComponents();
    }
    
    //---------------------------------------------------------------------------
    // Create a variable to hold a list of listeners,
    protected EventListenerList ListenerList = new EventListenerList();
    // Add an event listener to the list.
    public void AddEventListener(GUIeventListener Listener) {
        ListenerList.add(GUIeventListener.class, Listener);
    }

    // Remove an event listener from the list.
    public void RemoveEventListener(GUIeventListener Listener) {
        ListenerList.remove(GUIeventListener.class, Listener);
    }
    // Fire the event, tell everyone that something has happened.
    public void FireEvent(Object obj) {
        Object[] Listeners = ListenerList.getListenerList();
        // Process each of the event listeners in turn.
        for (int i = 0; i < Listeners.length; i++) {
            if (Listeners[i] == GUIeventListener.class) {
                ((GUIeventListener) Listeners[i + 1]).onChangeGUI(obj);
            }
        }
    }
    //---------------------------------------------------------------------------
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtParameter = new javax.swing.JTextField();
        btFireEvent = new javax.swing.JButton();

        txtParameter.setText("parameter");

        btFireEvent.setText("Fire Event");
        btFireEvent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFireEventActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btFireEvent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtParameter, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btFireEvent)
                    .addComponent(txtParameter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btFireEventActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFireEventActionPerformed
        FireEvent(txtParameter.getText());
    }//GEN-LAST:event_btFireEventActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btFireEvent;
    private javax.swing.JTextField txtParameter;
    // End of variables declaration//GEN-END:variables

}
